import type { Metadata } from 'next'
import { Inter, Red_Hat_Display } from 'next/font/google'
import './globals.css'
import LeftNavbarList from '@/components/LeftNavbarList'
import TopNavbar from '@/components/TopNavbar'

const inter = Inter({ subsets: ['latin'] })

const redHatDisplay = Red_Hat_Display({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`md:flex ${redHatDisplay.className}`}>
        <LeftNavbarList />
        <div className='md:flex md:flex-col w-full'>
          <TopNavbar />
          {children}
        </div>
      </body>
    </html>
  )
}
